version: '3'

services:
  chrome:
    image: kasmweb/chrome:1.9.0
    container_name: chrome
    environment:
      - VNC_PW=password
      - VNC_RESOLUTION=2880x1800
      - TZ=Asia/Shanghai
    ports:
      - '6901:6901'
    networks:
      - backend

networks:
  backend:
    external: true
