version: '3'

services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.1
    container_name: xxl-job-admin
    environment:
      - PARAMS=neo4j/XLrootJYD713
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_db_temporal_timezone=Asia/Shanghai
      - NEO4J_dbms_db_timezone=SYSTEM
      - TZ=Asia/Shanghai
    volumes:
      - /opt/volumes/neo4j/data:/data
      - /opt/volumes/neo4j/logs:/logs
      - /opt/volumes/extra:/extra
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    networks:
      - backend

networks:
  backend:
    external: true
