#!/usr/bin/ruby

#sudo gem update --system
#sudo gem sources --add https://gems.ruby-china.com/ --remove https://rubygems.org/
#sudo gem install colorize

require 'colorize'
require 'socket'
require 'etc'

def warn
  system "echo 'bin/init mysql-cluster|mariadb-cluster|postgresql-repmgr|postgresql-cluster|rabbitmq-cluster|redis-sentinel|redis-cluster|mongodb-cluster|elasticsearch-cluster|clickhouse-cluster|flink-cluster|kafka-cluster|nacos-cluster|logstash|cerebro|neo4j|canal|zipkin|sentinel|seata|nginx|minio|env'"
end

# TODO jenkins

def exec(cmd)
  #noinspection RubyResolve
  puts "#{"==>".blue.bold} #{cmd.red.bold}"
  system cmd
end

#noinspection RubyNilAnalysis
ip  = Socket.ip_address_list.detect { |x| x.ipv4_private? }.ip_address
num = Etc.nprocessors
app = ARGV[0]
warn && exit unless app

case app
  when 'canal'
    exec 'docker build -t canal-server ~/bin/module/canal/'
    exec 'docker rm -f canal-server'
    exec "docker run -d --net backend --name canal-server -p 11111:11111 -v /opt/volumes/extra:/extra canal-server"
  when 'mariadb-cluster'
    path = "~/bin/module/mariadb/mariadb-cluster"
    exec "docker-compose -f #{path}/docker-compose.yml up -d"
  when 'postgresql-repmgr'
    path = "~/bin/module/postgresql/postgresql-repmgr"
    exec "docker-compose -f #{path}/docker-compose.yml up -d"
  when 'postgresql-cluster'
    path = "~/bin/module/postgresql/postgresql-cluster"
    exec "docker-compose -f #{path}/docker-compose.yml up -d"
  when 'rabbitmq-cluster'
    path = "~/bin/module/rabbitmq/rabbitmq-cluster"
    exec "docker-compose -f #{path}/docker-compose.yml up -d"
  when 'neo4j'
    path = "~/bin/module/neo4j"
    exec "docker-compose -f #{path}/docker-compose.yml up -d"
  when 'mysql-cluster'
    path = "~/bin/module/mysql/mysql-cluster"
    exec "docker-compose -f #{path}/docker-compose.yml up -d"
  when 'redis-sentinel'
    path = "~/bin/module/redis/redis-sentinel"
    exec "docker-compose -f #{path}/docker-compose.yml up -d"
  when 'redis-cluster'
    path = "~//bin/module/redis/redis-cluster"
    exec "docker-compose -f #{path}/docker-compose.yml up -d"
  when 'mongodb-cluster'
    path = "~/bin/module/mongodb/mongodb-cluster"
    exec "docker-compose -f #{path}/docker-compose.yml up -d"
  when 'elasticsearch-cluster'
    path = "~/bin/module/elasticsearch/elasticsearch-cluster"
    exec "docker-compose -f #{path}/docker-compose.yml up -d"
  when 'logstash'
    path = "~/bin/module/logstash"
    exec "docker-compose -f #{path}/docker-compose.yml up -d"
  when 'cerebro'
    path = "~/bin/module/cerebro"
    exec "docker-compose -f #{path}/docker-compose.yml up -d"
  when 'clickhouse-cluster'
    path = "~/bin/module/clickhouse/clickhouse-cluster"
    exec "docker-compose -f #{path}/docker-compose.yml up -d"
  when 'flink-cluster'
    path = "~/bin/module/flink/flink-cluster"
    exec "NUM=#{num} docker-compose -f #{path}/docker-compose.yml up -d"
  when 'kafka-cluster'
    path = "~/bin/module/kafka/kafka-cluster"
    exec "IP=#{ip} docker-compose -f #{path}/docker-compose.yml up -d"
  when 'nacos-cluster'
    path = "~/bin/module/nacos/nacos-cluster"
    exec "docker-compose -f #{path}/docker-compose.yml up -d"
  when 'zipkin'
    exec 'docker build -t zipkin-server ~/bin/module/zipkin/'
    exec 'docker rm -f zipkin-server'
    exec 'docker run -d --net backend --name zipkin-server -p 9411:9411 -v /etc/localtime:/etc/localtime -v /opt/volumes/extra:/extra zipkin-server --link rabbitmq'
  when 'sentinel'
    exec 'docker build -t sentinel-server ~/bin/module/sentinel/'
    exec 'docker rm -f sentinel-server'
    exec 'docker run -d --net host    --name sentinel-server -v /etc/localtime:/etc/localtime -v /opt/volumes/extra:/extra sentinel-server'
  when 'nginx'
    exec 'docker build -t nginx-server ~/bin/module/nginx/'
    exec 'docker rm -f nginx-server'
    exec 'docker run -d --net backend --name nginx-server -p 80:80 -v ~/frontend:/frontend -v /opt/volumes/extra:/extra nginx-server'
  when 'minio'
    exec 'docker build -t minio-server ~/bin/module/minio/'
    exec 'docker rm -f minio-server'
    exec 'docker run -d --net backend --name minio-server -p 8998:9000 -p 8997:8997 -v /opt/volumes/minio:/data -v ~/config/minio:/root/.minio -v /opt/volumes/extra:/extra -v /etc/localtime:/etc/localtime minio-server server /data --console-address ":8997"'
  when 'seata'
    exec "docker build -t seata-server --build-arg IP='#{ip}' ~/bin/module/seata/"
    exec 'docker rm -f seata-server'
    exec 'docker run -d --net backend --name seata-server -p 8091:8091 -v /etc/localtime:/etc/localtime -v /opt/volumes/extra:/extra seata-server'
  when 'env'
    exec 'docker network create backend'
  else
    warn
end
