#!/usr/bin/ruby

#sudo gem update --system
#sudo gem sources --add https://gems.ruby-china.com/ --remove https://rubygems.org/
#sudo gem install colorize

require 'colorize'

def warn
  system "echo 'bin/init mysql|mysql5|mariadb|mycat|postgresql|rabbitmq|redis|mongodb|clickhouse|clickhouse-cluster|nacos|zipkin|sentinel|seata|nginx|fastdfs|minio|alpine|ubuntu|debian|arch|java|env'"
end

# TODO jenkins

def exec(cmd)
  #noinspection RubyResolve
  puts "#{"==>".blue.bold} #{cmd.red.bold}"
  system cmd
end

app = ARGV[0]
warn && exit unless app

case app
  when 'mysql'
    exec 'docker build -t mysql-server ~/bin/dockerfile/mysql/'
    exec 'docker rm -f mysql-server'
    exec "docker run -d --net backend --name mysql-server -p 3306:3306 -v ~/volume/mysql:/var/lib/mysql -v /home:/extra/home --restart=always --privileged=true mysql-server:latest --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --lower_case_table_names=1 --default-time_zone='+8:00'"
  when 'mysql5'
    exec 'docker build -t mysql5-server ~/bin/dockerfile/mysql5/'
    exec 'docker rm -f mysql5-server'
    exec "docker run -d --net backend --name mysql5-server -p 3307:3306 -v ~/volume/mysql5:/var/lib/mysql -v /home:/extra/home --restart=always --privileged=true mysql5-server:latest --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --lower_case_table_names=1 --default-time_zone='+8:00'"
  when 'mariadb'
    exec 'docker build -t mariadb-server ~/bin/dockerfile/mariadb/'
    exec 'docker rm -f mariadb-server'
    exec "docker run -d --net backend --name mariadb-server -p 3308:3306 -v ~/volume/maria:/var/lib/mysql -v /home:/extra/home -v /etc/localtime:/etc/localtime --restart=always --privileged=true mariadb-server:latest --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --lower_case_table_names=1 --default-time_zone='+8:00'"
  when 'mycat'
    exec 'docker build -t mycat-server ~/bin/dockerfile/mycat/'
    exec 'docker rm -f mycat-server'
    exec "docker run -d --net backend --name mycat-server -p 8066:8066 -p 9066:9066 -v /home:/extra/home --restart=always --privileged=true mycat-server:latest"
  when 'postgresql'
    exec 'docker build -t postgresql-server ~/bin/dockerfile/postgresql/'
    exec 'docker rm -f postgresql-server'
    exec 'docker run -d --net backend --name postgresql-server -p 5432:5432 -v ~/volume/pgdata:/var/lib/postgresql/data -v /home:/extra/home --restart=always --privileged=true postgresql-server:latest'
  when 'rabbitmq'
    exec 'docker build -t rabbitmq-server ~/bin/dockerfile/rabbitmq/'
    exec 'docker rm -f rabbitmq-server'
    exec 'docker run -d --net backend --name rabbitmq-server -p 15672:15672 -p 5672:5672 -v ~/volume/rabbitmq:/var/lib/rabbitmq -v /home:/extra/home --hostname rabbitmq-server --restart=always --privileged=true rabbitmq-server:latest'
  when 'redis'
    exec 'docker build -t redis-server ~/bin/dockerfile/redis/'
    exec 'docker rm -f redis-server'
    exec 'docker run -d --net backend --name redis-server -p 6379:6379 -v ~/volume/redis:/data -v /home:/extra/home --restart=always --privileged=true redis-server:latest --requirepass "XLrootJYD713"'
  when 'mongodb'
    exec 'docker build -t mongodb-server ~/bin/dockerfile/mongodb/'
    exec 'docker rm -f mongodb-server'
    exec 'docker run -d --net backend --name mongodb-server -p 27017:27017 -v ~/volume/mongo:/data/db -v /home:/extra/home --restart=always --privileged=true mongodb-server:latest'
  when 'clickhouse'
    exec 'docker build -t clickhouse-server ~/bin/dockerfile/clickhouse/'
    exec 'docker rm -f clickhouse-server'
    exec 'docker run -d --net backend --name clickhouse-server --ulimit nofile=262144:262144 -p 8123:8123 -p 8999:9000 -v ~/volume/clickhouse:/var/lib/clickhouse -v /home:/extra/home --restart=always --privileged=true clickhouse-server:latest'
  when 'clickhouse-cluster'
    exec 'docker build -t clickhouse-shard1-replica1 --build-arg NODE="01-1" ~/bin/dockerfile/clickhouse/cluster/'
    exec 'docker rm -f clickhouse-shard1-replica1'

    exec 'docker build -t clickhouse-shard1-replica2 --build-arg NODE="01-2" ~/bin/dockerfile/clickhouse/cluster/'
    exec 'docker rm -f clickhouse-shard1-replica2'

    exec 'docker build -t clickhouse-shard2-replica1 --build-arg NODE="02-1" ~/bin/dockerfile/clickhouse/cluster/'
    exec 'docker rm -f clickhouse-shard2-replica1'

    exec 'docker build -t clickhouse-shard2-replica2 --build-arg NODE="02-2" ~/bin/dockerfile/clickhouse/cluster/'
    exec 'docker rm -f clickhouse-shard2-replica2'

    exec 'docker build -t clickhouse-shard3-replica1 --build-arg NODE="03-1" ~/bin/dockerfile/clickhouse/cluster/'
    exec 'docker rm -f clickhouse-shard3-replica1'

    exec 'docker build -t clickhouse-shard3-replica2 --build-arg NODE="03-2" ~/bin/dockerfile/clickhouse/cluster/'
    exec 'docker rm -f clickhouse-shard3-replica2'

    exec 'docker rm -f zookeeper-clickhouse'
    exec 'docker run -d --net backend --name zookeeper-clickhouse --restart=always --privileged=true zookeeper:3.6.3'
    sleep 30

    exec 'docker run -d --net backend --name clickhouse-shard1-replica1 --ulimit nofile=262144:262144 -p 18011:8123 -v ~/volume/clickhouse-shard1-replica1:/var/lib/clickhouse -v /home:/extra/home --restart=always --privileged=true clickhouse-shard1-replica1:latest'

    exec 'docker run -d --net backend --name clickhouse-shard1-replica2 --ulimit nofile=262144:262144 -p 18012:8123 -v ~/volume/clickhouse-shard1-replica2:/var/lib/clickhouse -v /home:/extra/home --restart=always --privileged=true clickhouse-shard1-replica2:latest'

    exec 'docker run -d --net backend --name clickhouse-shard2-replica1 --ulimit nofile=262144:262144 -p 18021:8123 -v ~/volume/clickhouse-shard2-replica1:/var/lib/clickhouse -v /home:/extra/home --restart=always --privileged=true clickhouse-shard2-replica1:latest'

    exec 'docker run -d --net backend --name clickhouse-shard2-replica2 --ulimit nofile=262144:262144 -p 18022:8123 -v ~/volume/clickhouse-shard2-replica2:/var/lib/clickhouse -v /home:/extra/home --restart=always --privileged=true clickhouse-shard2-replica2:latest'

    exec 'docker run -d --net backend --name clickhouse-shard3-replica1 --ulimit nofile=262144:262144 -p 18031:8123 -v ~/volume/clickhouse-shard3-replica1:/var/lib/clickhouse -v /home:/extra/home --restart=always --privileged=true clickhouse-shard3-replica1:latest'

    exec 'docker run -d --net backend --name clickhouse-shard3-replica2 --ulimit nofile=262144:262144 -p 18032:8123 -v ~/volume/clickhouse-shard3-replica2:/var/lib/clickhouse -v /home:/extra/home --restart=always --privileged=true clickhouse-shard3-replica2:latest'
  when 'nacos'
    exec 'docker build -t nacos-server ~/bin/dockerfile/nacos/'
    exec 'docker rm -f nacos-server'
    exec 'docker run -d --net backend --name nacos-server -p 8848:8848 -v /home:/extra/home --restart=always --privileged=true nacos-server:latest'
  when 'zipkin'
    exec 'docker build -t zipkin-server ~/bin/dockerfile/zipkin/'
    exec 'docker rm -f zipkin-server'
    exec 'docker run -d --net backend --name zipkin-server -p 9411:9411 -v /etc/localtime:/etc/localtime -v /home:/extra/home --restart=always --privileged=true zipkin-server:latest --link rabbitmq'
  when 'sentinel'
    exec 'docker build -t sentinel-server ~/bin/dockerfile/sentinel/'
    exec 'docker rm -f sentinel-server'
    exec 'docker run -d --net host    --name sentinel-server -v /etc/localtime:/etc/localtime -v /home:/extra/home --restart=always --privileged=true sentinel-server:latest'
  when 'nginx'
    exec 'docker build -t nginx-server ~/bin/dockerfile/nginx/'
    exec 'docker rm -f nginx-server'
    exec 'docker run -d --net backend --name nginx-server -p 80:80 -v ~/frontend:/frontend -v /home:/extra/home --restart=always --privileged=true nginx-server:latest'
  when 'fastdfs'
    exec 'docker build -t fastdfs-server ~/bin/dockerfile/fastdfs/'
    exec 'docker rm -f fastdfs-server'
    exec 'docker run -d --net host    --name fastdfs-server -v ~/volume/fastdfs:/data -v /home:/extra/home --restart=always --privileged=true fastdfs-server:latest'
  when 'minio'
    exec 'docker build -t minio-server ~/bin/dockerfile/minio/'
    exec 'docker rm -f minio-server'
    exec 'docker run -d --net backend --name minio-server -p 8998:9000 -p 8997:8997 -v ~/volume/minio:/data -v ~/config/minio:/root/.minio -v /home:/extra/home -v /etc/localtime:/etc/localtime --restart=always --privileged=true minio-server:latest server /data --console-address ":8997"'
  when 'seata'
    exec 'docker build -t seata-server ~/bin/dockerfile/seata/'
    exec 'docker rm -f seata-server'
    exec 'docker run -d --net backend --name seata-server -p 8091:8091 -v /etc/localtime:/etc/localtime -v /home:/extra/home --restart=always --privileged=true seata-server:latest'
  when 'alpine'
    exec 'docker build -t alpine-os ~/bin/dockerfile/alpine/'
    exec 'docker rm -f alpine-os'
    exec 'docker run -d --net backend --name alpine-os -v /home:/extra/home -it alpine-os:latest sh'
  when 'ubuntu'
    exec 'docker build -t ubuntu-os ~/bin/dockerfile/ubuntu/'
    exec 'docker rm -f ubuntu-os'
    exec 'docker run -d --net backend --name ubuntu-os -v /etc/localtime:/etc/localtime -v /home:/extra/home -it ubuntu-os:latest /bin/bash'
  when 'debian'
    exec 'docker build -t debian-os ~/bin/dockerfile/debian/'
    exec 'docker rm -f debian-os'
    exec 'docker run -d --net backend --name debian-os -v /home:/extra/home -it debian-os:latest /bin/bash'
  when 'arch'
    exec 'docker build -t arch-os ~/bin/dockerfile/arch/'
    exec 'docker rm -f arch-os'
    exec 'docker run -d --net backend --name arch-os -v /home:/extra/home -it arch-os:latest /bin/bash'
  when 'java'
    exec 'docker build -t jre-alpine ~/bin/dockerfile/java/'
  when 'env'
    exec 'docker network create backend'
  else
    warn
end
