version: '3'

services:
  xxl_job_admin:
    image: xuxueli/xxl-job-admin:2.3.1
    container_name: xxl_job_admin
    environment:
      - PARAMS=--spring.datasource.url=jdbc:mysql://mysql-master:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai  --spring.datasource.password=XLrootJYD713  --xxl.job.accessToken=XLrootJYD713
    volumes:
      - /opt/volumes/xxl_job_admin/logs:/data/applogs
    ports:
      - '8080:8080'
    networks:
      - backend

networks:
  backend:
    external: true
