FROM canal/canal-admin:v1.1.5

ENV LANG zh_CN.UTF-8
ENV TZ Asia/Shanghai

ENV server.port 8089
ENV canal.adminUser admin
ENV canal.adminPasswd XLrootJYD713

ENV spring.datasource.address mysql-server:3306
ENV spring.datasource.database canal_manager
ENV spring.datasource.username root
ENV spring.datasource.password XLrootJYD713
