version: '3'
services:

  flink-jobmanager:
    image: flink:1.14.0-scala_2.12-java11
    container_name: flink-jobmanager
    hostname: flink-jobmanager
    ports:
      - "8079:8081"
    networks:
      - backend
    command: jobmanager
    environment:
      - TZ=Asia/Shanghai
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        jobmanager.memory.process.size: ${MEM}G

  flink-taskmanager1:
    image: flink:1.14.0-scala_2.12-java11
    container_name: flink-taskmanager1
    hostname: flink-taskmanager1
    depends_on:
      - flink-jobmanager
    networks:
      - backend
    command: taskmanager
    environment:
      - TZ=Asia/Shanghai
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: ${NUM}
        taskmanager.memory.process.size: ${MEM}G

  flink-taskmanager2:
    image: flink:1.14.0-scala_2.12-java11
    container_name: flink-taskmanager2
    hostname: flink-taskmanager2
    depends_on:
      - flink-jobmanager
    networks:
      - backend
    command: taskmanager
    environment:
      - TZ=Asia/Shanghai
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: ${NUM}
        taskmanager.memory.process.size: ${MEM}G

  flink-taskmanager3:
    image: flink:1.14.0-scala_2.12-java11
    container_name: flink-taskmanager3
    hostname: flink-taskmanager3
    depends_on:
      - flink-jobmanager
    networks:
      - backend
    command: taskmanager
    environment:
      - TZ=Asia/Shanghai
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: ${NUM}
        taskmanager.memory.process.size: ${MEM}G

  flink-taskmanager4:
    image: flink:1.14.0-scala_2.12-java11
    container_name: flink-taskmanager4
    hostname: flink-taskmanager4
    depends_on:
      - flink-jobmanager
    networks:
      - backend
    command: taskmanager
    environment:
      - TZ=Asia/Shanghai
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: ${NUM}
        taskmanager.memory.process.size: ${MEM}G

networks:
  backend:
    external: true
