version: '3'

services:
  proxypool:
    build: ctx
    container_name: proxypool
    environment:
      - DB_CONN=redis://:XLrootJYD713@redis-master:6379/0
    networks:
      - backend
    ports:
      - '5010:5010'

networks:
  backend:
    external: true
