FROM bitnami/elasticsearch:7.17.7

RUN wget -O /bitnami/elasticsearch/plugins/analysis-ik-7.17.7.zip https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.17.7/elasticsearch-analysis-ik-7.17.7.zip
