version: '3'

services:
  ubuntu:
    image: ubuntu:focal-20220105
    container_name: ubuntu
    hostname: ubuntu
    networks:
      - backend
    tty: true
    environment:
      - TZ=Asia/Shanghai

networks:
  backend:
    external: true
