FROM canal/canal-server:v1.1.5

ENV LANG zh_CN.UTF-8
ENV TZ Asia/Shanghai

ENV canal.admin.manager canal-admin-server:8089
ENV canal.admin.port 11111
ENV canal.admin.user admin
ENV canal.admin.passwd 4ACFE3202A5FF5CF467898FC58AAB1D615029441

ENV canal.instance.master.address mysql-server:3306
ENV canal.instance.dbUsername canal
ENV canal.instance.dbPassword canal
