FROM canal/canal-server:v1.1.5

ENV LANG zh_CN.UTF-8
ENV TZ Asia/Shanghai

ENV canal.instance.master.address mysql5-server:3306
ENV canal.instance.dbUsername root
ENV canal.instance.dbPassword XLrootJYD713
