version: "3"
services:

  seata-server:
    container_name: seata-server
    image: seataio/seata-server:1.6.1
    ports:
      - "8091:8091"
      - "7091:7091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file

networks:
  backend:
    external: true
