version: '3'

services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.8.0
    networks:
      - backend
    ports:
      - '2181:2181'
    volumes:
      - /opt/volumes/zookeeper:/bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - TZ=Asia/Shanghai
      - ZOO_SERVER_ID=1

networks:
  backend:
    external: true
