FROM registry.cn-hangzhou.aliyuncs.com/flink-streaming-platform-web/flink-web:flink-1.13.2

COPY libs /data/projects/flink-1.13.2/lib
COPY flink-conf.yaml /data/projects/flink-1.13.2/conf/flink-conf.yaml
