version: '3'
services:

  neo4j-server:
    image: neo4j-server
    container_name: neo4j-server
    environment:
      - NEO4J_AUTH=neo4j/XLrootJYD713
    volumes:
      - /opt/volumes/neo4j/data:/data
      - /opt/volumes/neo4j/logs:/logs
      - /opt/volumes/extra:/extra
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - backend

networks:
  backend:
    external: true
