version: '3'
services:

  postgresql-master:
    image: bitnami/postgresql:15.2.0
    container_name: postgresql-master
    networks:
      - backend
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=XLrootJYD713
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=XLrootJYD713
      - POSTGRESQL_USERNAME=pg
      - POSTGRESQL_PASSWORD=XLrootJYD713
      - POSTGRESQL_DATABASE=pg
      - TZ=Asia/Shanghai
    volumes:
      - postgresql-master:/bitnami/postgresql
      - ../conf/:/bitnami/postgresql/conf/conf.d/
  postgresql-worker1:
    image: bitnami/postgresql:15.2.0
    container_name: postgresql-worker1
    networks:
      - backend
    ports:
      - '5433:5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=XLrootJYD713
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=XLrootJYD713
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=XLrootJYD713
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - TZ=Asia/Shanghai
    volumes:
      - postgresql-worker1:/bitnami/postgresql
      - ../conf/:/bitnami/postgresql/conf/conf.d/
  postgresql-worker2:
    image: bitnami/postgresql:15.2.0
    container_name: postgresql-worker2
    networks:
      - backend
    ports:
      - '5434:5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=XLrootJYD713
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=XLrootJYD713
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=XLrootJYD713
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - TZ=Asia/Shanghai
    volumes:
      - postgresql-worker2:/bitnami/postgresql
      - ../conf/:/bitnami/postgresql/conf/conf.d/
  postgresql-worker3:
    image: bitnami/postgresql:15.2.0
    container_name: postgresql-worker3
    networks:
      - backend
    ports:
      - '5435:5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=XLrootJYD713
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=XLrootJYD713
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=XLrootJYD713
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - TZ=Asia/Shanghai
    volumes:
      - postgresql-worker3:/bitnami/postgresql
      - ../conf/:/bitnami/postgresql/conf/conf.d/

networks:
  backend:
    external: true

volumes:
  postgresql-master:
  postgresql-worker1:
  postgresql-worker2:
  postgresql-worker3:
