version: '3'
services:

  mysql-node:
    container_name: mysql-node
    image: bitnami/mysql:8.0.32
    ports:
      - '3306:3306'
    networks:
      - backend
    volumes:
      - ./conf/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
      - /opt/volumes/mysql-node:/bitnami/mysql
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=XLrootJYD713
      - MYSQL_ROOT_PASSWORD=XLrootJYD713
      - MYSQL_PASSWORD=XLrootJYD713
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_unicode_ci
      - TZ=Asia/Shanghai

networks:
  backend:
    external: true
