version: '3'
services:

  hdfs-namenode:
    container_name: hdfs-namenode
    image: gradiant/hdfs:3.2.2
    ports:
      - '8020:8020'
      - '50070:50070'
      - '9870:9870'
    networks:
      - backend
    volumes:
      - /opt/volumes/hdfs-namenode:/hadoop/dfs
    environment:
      - TZ=Asia/Shanghai
    command:
      - namenode
  hdfs-datanode:
    container_name: hdfs-datanode
    image: gradiant/hdfs:3.2.2
    networks:
      - backend
    volumes:
      - /opt/volumes/hdfs-datanode:/hadoop/dfs
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:8020
      - TZ=Asia/Shanghai
    command:
      - datanode

networks:
  backend:
    external: true
